workflows:
  android-workflow:
    name: Android APK Release
    environment:
      flutter: 3.41.6
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --release
          flutter build apk --release --split-per-abi
        artifacts:
          - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          